memory: 50m
cpu: 5%
disk: 200M
image: python
services:
  - name: python_server
    command: python -m wsgiref.simple_server
    restart:
      interval: 60
      limit: 5
endpoints:
  - name: http
    port: 8000
    type: infra



